/*(1) Content Posting: Write a few (4 to 5) queries that users need to sign up, to create or edit their profiles, to post an image,
or to add a new entry to their diaries.
*/
/*sign up*/
CREATE OR REPLACE FUNCTION add_user(IN_USER_NAME VARCHAR(20), IN_PWD VARCHAR(20))
  RETURNS VOID AS $$
BEGIN
  INSERT INTO USERS (user_name, password, url) VALUES (IN_USER_NAME, IN_PWD, 'http://Techies.com/'||IN_USER_NAME||'/');
END;
$$ LANGUAGE 'plpgsql' VOLATILE ;

SELECT add_user('JIM', '123');
SELECT * FROM users;

/*create profiles*/
INSERT INTO profile VALUES (1, 'JACK', 'GREEN', 18, '1100', 'WEST6',
                            'BROOKLYN', 'NY', 12345, 'I AM JACK', 'DATABASE LEARNER', 0, 1);

UPDATE profile SET  AGE = 19 WHERE profile_id = 1;

CREATE OR REPLACE FUNCTION add_profile(FIRST_NAME VARCHAR(10), LAST_NAME VARCHAR(10), AGE INTEGER,
  APT VARCHAR(30), STREET VARCHAR(30), CITY VARCHAR(15), STATE VARCHAR(15), ZIP INTEGER, GREETING TEXT,
  SELF_INTRODUCTION TEXT, PUBLICITY_LEVEL INTEGER, USER_ID INTEGER)
  RETURNS VOID AS $$
BEGIN
  INSERT INTO PROFILE
  VALUES
  (DEFAULT, FIRST_NAME, LAST_NAME, AGE, APT, STREET, CITY, STATE, ZIP, GREETING, SELF_INTRODUCTION, PUBLICITY_LEVEL, USER_ID);
END;
$$ LANGUAGE 'plpgsql';

SELECT add_profile('JACK', 'GREEN', 18, '1100', 'WEST6',
                            'BROOKLYN', 'NY', 12345, 'I AM JACK', 'DATABASE LEARNER', 0, 1);

SELECT * FROM profile;

/*edit profile*/

CREATE OR REPLACE FUNCTION edit_profile(IN_PROFILE_ID INTEGER, IN_FIRST_NAME VARCHAR(10), IN_LAST_NAME VARCHAR(10), IN_AGE INTEGER,
  IN_APT VARCHAR(30), IN_STREET VARCHAR(30), IN_CITY VARCHAR(15), IN_STATE VARCHAR(15), IN_ZIP INTEGER, IN_GREETING TEXT,
  IN_SELF_INTRODUCTION TEXT, IN_PUBLICITY_LEVEL INTEGER, IN_USER_ID INTEGER)
  RETURNS VOID AS $$
BEGIN
  UPDATE profile SET first_name=IN_FIRST_NAME, last_name=IN_LAST_NAME, age=IN_AGE,
  apt=IN_APT, street=IN_STREET, city=IN_CITY, state=IN_STATE, zip=IN_ZIP, greeting_everyone=IN_GREETING,
  self_introduction=IN_SELF_INTRODUCTION, publicity_level=IN_PUBLICITY_LEVEL, user_id=IN_USER_ID WHERE profile_id=IN_PROFILE_ID;
END;
$$ LANGUAGE 'plpgsql';

/*add a new entry to their diaries*/
CREATE OR REPLACE FUNCTION add_diary(TITLE TEXT, PUBLICITY_LEVEL INTEGER, USER_ID INTEGER)
  RETURNS int AS $$
BEGIN
  INSERT INTO diary VALUES(DEFAULT, TITLE, NOW(), NOW(), PUBLICITY_LEVEL, USER_ID);
END;
$$ LANGUAGE 'plpgsql';
